#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

function main() {
  const args = process.argv.slice(2);
  const runId = args[0] || `run-demo-${timestamp()}`;
  const projectId = args[1] || 'proj-demo';
  const runDir = path.resolve(process.cwd(), '.ai/selene/runs', runId);

  fs.mkdirSync(runDir, { recursive: true });

  writeJson(path.join(runDir, 'request.json'), {
    run_id: runId,
    project_id: projectId,
    project_name: 'Selene Demo Project',
    goal: 'Run Selene remote sync demo',
    intent: 'system_test',
    requires_spec: true,
    requires_verification: true,
    base_commit: 'demo-commit',
    branch: `selene/${runId}`,
    actor_id: 'demo-user',
    editor: 'manual',
  });

  writeJson(path.join(runDir, 'routing.json'), {
    routed_by: 'selene',
    created_at: new Date().toISOString(),
  });

  writeJson(path.join(runDir, 'spec.sync.json'), {
    spec_id: `spec-${runId}`,
    project_id: projectId,
    run_id: runId,
    goal: 'Run Selene remote sync demo',
    intent: 'system_test',
    status: 'draft',
    target_files: ['demo/file.ts'],
    verification_plan: [
      {
        name: 'smoke',
        command: 'echo smoke',
        required: true,
      },
    ],
    exit_criteria: ['Remote sync succeeds'],
    split_tasks: [
      {
        task_id: `task-${runId}`,
        target_files: ['demo/file.ts'],
        verification_plan: [
          {
            name: 'smoke',
            command: 'echo smoke',
            required: true,
          },
        ],
        status: 'open',
      },
    ],
    content_md: '# Selene Demo\n\nThis is a generated demo run.',
  });

  writeJson(path.join(runDir, 'tasks.json'), [
    {
      task_id: `task-${runId}`,
      run_id: runId,
      spec_id: `spec-${runId}`,
      owner: 'demo-user',
      status: 'open',
      base_commit: 'demo-commit',
      branch: `selene/${runId}`,
      target_files: ['demo/file.ts'],
      verification_plan: [
        {
          name: 'smoke',
          command: 'echo smoke',
          required: true,
        },
      ],
      result: null,
    },
  ]);

  fs.writeFileSync(
    path.join(runDir, 'events.jsonl'),
    `${JSON.stringify({
      run_id: runId,
      task_id: `task-${runId}`,
      actor_id: 'demo-user',
      step: 'demo_created',
      status: 'ok',
      failure_type: null,
      payload_json: { note: 'Demo run scaffolded locally' },
    })}\n`,
    'utf8',
  );

  writeJson(path.join(runDir, 'result.json'), {
    run_id: runId,
    spec_id: `spec-${runId}`,
    status: 'success',
    changed_files: [],
    verification_summary: [
      {
        name: 'smoke',
        status: 'passed',
      },
    ],
    retry_count: 0,
    failure_type: null,
    human_handoff: false,
    notes: 'Generated by new_demo_run.js',
  });

  console.log(runDir);
}

function timestamp() {
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');
  const hh = String(now.getHours()).padStart(2, '0');
  const mi = String(now.getMinutes()).padStart(2, '0');
  const ss = String(now.getSeconds()).padStart(2, '0');
  return `${yyyy}${mm}${dd}-${hh}${mi}${ss}`;
}

function writeJson(filePath, data) {
  fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

main();
